#
# Prerequisites:
# - tempo-operator must be installed (community version + cert-manager or via OLM)
# - opentelemetry-operator must be installed
# - minio must be installed in the minio namespace (see /minio.yaml)
#
apiVersion: kuttl.dev/v1beta1
kind: TestSuite
testDirs:
  - ./tests/e2e-openshift/
timeout: 150
