apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMonolithic
metadata:
  name: sample
spec:
  storage:
    traces:
      backend: memory
  jaegerui:
    enabled: true
    ingress:
      enabled: true
